### ISSUE TITLE
Linux keybinding conflicts with `find-and-replace:select-undo`

### ISSUE THREAD

**Issue by dsandstrom** [atom/encoding-selector#10]
I can disable this package for now, but maybe pick a new keymap for Linux/Win.  Maybe `alt-u`?

**Comment by dsandstrom** [comment]
Would you take a pull request?  What should I change it to?

**Comment by benogle** [comment]
Yes a PR would be accepted for alt-u on linux (provided nothing else uses alt-u).

**Comment by kevinsawicki** [comment]
Fixed by #17

**Comment by ricardograca** [comment]
So, [git-diff-details](https://github.com/samu/git-diff-details/issues/47) also uses `Alt+U`, so how are these situations resolved?

Actually, it seems that `find-and-replace` actually uses `Ctrl+U` not `Ctrl+Shift+U` so the linux keymap can be changed to match the others safely now. I'll provide a PR soon.
