### ISSUE TITLE
Recognise encoding from html meta tag

### ISSUE THREAD

**Issue by nice-shot** [atom/encoding-selector#25]
Hi,

It would be very cool if the automatic encoding selector was able to recognise xml and html meta tags. For example:
```html
<meta content="text/html; charset=cp-1255" http-equiv="Content-Type">
```
Or
```xml
<?xml version="1.0" encoding="CP-1256"?>
```

(I guess the xml one is more common)

**Comment by henrik-ryom** [comment]
+1

**Comment by damieng** [comment]
We have no plans to expand the scope of encoding-selector to be able to parse and understand specific document structures.
