### ISSUE TITLE
Consider adding a tooltip to status view

### ISSUE THREAD

**Issue by Tyriar** [atom/encoding-selector#26]
Original issue files in atom/status-bar: atom/status-bar#81

**Comment by damieng** [comment]
Clicking the UTF8 text today shows you the list of various encodings in a non-destructive manner. I think that shows quite a good explanation of what it does. I can't really think what a tooltip would add or say beyond that.

**Comment by bronson** [comment]
What you say is true for experienced Atom users who aren't afraid to click on things.  However, I don't think it's quite so obvious to new Atom users, or people who aren't familiar with character encodings.

Sure, I guessed correctly when I saw "ISO 8859-1" .  But, if I saw a tooltip saying "This file uses the ISO 8859-1 character set", I wouldn't need to guess at all.

I think a tooltip would add some confidence and discoverability, even in so simple a status display.  I'd be happy to bang together a PR.

**Comment by bronson** [comment]
Just noticed: the branch name is similarly obvious, yet it has a tooltip.  I'm glad it does!

**Comment by damieng** [comment]
If anyone wants to create a PR for this I can try and make sure it gets merged in a timely manner.

**Comment by bronson** [comment]
Very cool.  I'd be happy to but it will have to be next week.

**Comment by bronson** [comment]
A week...  or three.

Tell me if #45 needs any changes.
