### ISSUE TITLE
Uncaught (in promise) Error: Encoding not recognized: 'windows866' (searched as: 'windows866')

### ISSUE THREAD

**Issue by idfumg** [atom/encoding-selector#36]
Good day!
I have the same problem as in the #23.
I saw you fixed it in the [c664409](https://github.com/atom/encoding-selector/commit/c66440991807db33671fe9d66fb3e029966ed595) in encoding-selector.
And this working now for me if I select particular encoding for a separate file.
But in the atom default setting I still have to choose 'windows866' encoding.
And it cause of the same error when opening a file in the 'iconv' module.
I have a vanilla atom editor with only preinstalled packages v.1.9.9 (in v.1.10.0-beta6 the same behaviour).
May be this enum value in the atom defaults have to be changed to 'cp866' too?

**Comment by 50Wliu** [comment]
Cannot confirm.  This works for me on 1.11.0-dev-a0f7669.

**Comment by damieng** [comment]
Confirmed repro here on Windows 10.
