### ISSUE TITLE
UTF8 File with BOM opened in Atom cause the BOM to be moved

### ISSUE THREAD

**Issue by Gulix** [atom/encoding-selector#50]
### Description

File previously created by another editor, in UTF8 with BOM, is messed up when edited by ATOM. 
The BOM is treated as a normal character.

### Steps to Reproduce

I got a simple text file encoded in UTF8 with BOM : 

![image](https://user-images.githubusercontent.com/9212910/27123558-8b778e5a-50ee-11e7-94f8-df7a7ef7441b.png)

The `ef bb bf` code is the BOM. Then I open this file with atom.
When I select all the content of the file, I got this : 

![image](https://user-images.githubusercontent.com/9212910/27123831-512a914c-50ef-11e7-9822-259d1df4edba.png)

6 characters selected ? I only see 5. The BOM is present, as an invisible character. Also, when my cursor is on 1,1, and I moved to the right, the cursor is on 1,2 and still before the actual characters.

I then go to the start of my file (Ctrl+Start) and a new character. The file looks like this in Atom : 

![image](https://user-images.githubusercontent.com/9212910/27123957-bec2a6b8-50ef-11e7-8dc4-fa1be6745458.png)

When I open it with an hexa editor, I got this : 

![image](https://user-images.githubusercontent.com/9212910/27123977-d2ed1cea-50ef-11e7-8b71-acc290e215c2.png)

The BOM character is now inside the body of the file, not at its start. Needless to say, it provokes havoc with some tools I use.

Is there a way to ignore the BOM character ? In order to prevent this ?

**Expected behavior:** The BOM stays always in the shadow, at the head of the file.

**Actual behavior:** The BOM is moved inside the file as a regular character.

**Reproduces how often:** Everytime

### Versions

1.17.2 on Windows 7

**Comment by 50Wliu** [comment]
This is a larger issue with Atom: see atom/atom#3427.

**Comment by ariferol01** [comment]
maybe someone can write a package for this issue
